version: '3'

services:
  jenkins:
    image: jenkins/jenkins:2.263.3
    volumes:
      - jenkins-volume:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Dpermissive-script-security.enabled=true
    restart: always

  tomcat:
    image: tomcat:9.0
    volumes:
      - tomcat-volume:/usr
      - ./context.xml:/tmp/context.xml
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
      - "8090:8080"
    restart: always
    command: >
      /bin/bash -c "
        rm -rf /usr/local/tomcat/webapps;
        cp -r /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps;
        cp /tmp/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml;
        catalina.sh run
      "

  sonarqube:
    image: sonarqube:8.6.1-community
    volumes:
      - sonarqube-volume:/opt/sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    restart: always

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    volumes:
      - ./artifactory/var/:/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    restart: always
  
  gitea:
    image: gitea/gitea:1.12.4
    volumes:
      - gitea-volume:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mariadb-volume:/var/lib/mysql

volumes:
  jenkins-volume:
  tomcat-volume:
  sonarqube-volume:
  gitea-volume:
  mariadb-volume:
