name: Kubectl

on:
  push:
    branches: [ master ]
    paths:
      - 'kubectl/**'
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./kubectl --file kubectl/Dockerfile --tag vigneshsweekaran/kubectl:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Docker Image
      run: docker push vigneshsweekaran/kubectl:latest
