name: Ubuntu ssh enabled
on:
  push:
    branches: [ master ]
    paths:
      - 'ubuntu-ssh-enabled/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./ubuntu-ssh-enabled --file ubuntu-ssh-enabled/Dockerfile --tag vigneshsweekaran/ubuntu-ssh-enabled:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Docker Image
      run: docker push vigneshsweekaran/ubuntu-ssh-enabled:latest
